export default {
  LANDING: "/",
  HOME: "/home",
  FAVOURITES: "/favourites",
  PRODUCT: "/zkapp",
  CATEGORY: "/category",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  FORGOT_PASSWORD: "/forgot",
  PROFILE: "/profile",
  RESET_ACCOUNT: "/reset-account",
  SETTINGS: "/settings",
  VERIFY_EMAIL: "/verify-email",
  PENDING_VERIFICATION: "/pending-verification",
  CATEGORIES: "/categories",
  PRIVACY: "/privacy-policy",
  NEWS: "/news",
  ALL_APPS: "/all-zkapps",
};
