export default {
  LANDING: "/",
  HOME: "/home",
  FAVOURITES: "/favourites",
  PRODUCT: "/product",
  CATEGORY: "/category",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  FORGOT_PASSWORD: "/forgot",
  PROFILE: "/profile",
  RESET_ACCOUNT: "/reset-account",
  SETTINGS: "/settings",
  VERIFY_EMAIL: "/verify-email",
};
